package com.floatCloud.loveLearn.sysOa.dao.mapper;

import com.floatCloud.loveLearn.sysOa.dao.domain.SysAclModule;

public interface SysAclModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insert(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insertSelective(SysAclModule record);
}