package com.floatCloud.loveLearn.sysOa.dao.mapper;

import com.floatCloud.loveLearn.sysOa.dao.domain.SysDept;

public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insertSelective(SysDept record);
}