package com.floatCloud.loveLearn.sysOa.dao.mapper;

import com.floatCloud.loveLearn.sysOa.dao.domain.SysRoleUser;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insert(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insertSelective(SysRoleUser record);
}