devtools:
  livereload:
    enabled: true #是否支持lovereload
    port: 35729
  restart:
    enabled: true #是否支持热部署
    additional-paths: src/main/java

#设置访问端口
server:
  port: 8081

#spring配置
spring:
  # mvc:
  #  view: #配置视图解析器
  #   prefix: classpath:/WEB-INF/JSP/
  #   suffix: .jsp
  datasource:
    #com.mysql.cj.jdbc.Driver 驱动 必须设置时区serverTimezone
    url: jdbc:mysql://localhost:3306/lovecloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root #默认提醒的 data-username data-password 中- 会导致编译错误 报错是 ''@'localhost' (using password NO)
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

# spring boot 使用thymeleaf 进行页面渲染更加方便
  thymeleaf:
    cache: false #关闭缓存
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  #全局的映射，不用在xml文件写实体类的全路径,多个路径之间用逗号隔开
  type-aliases-package: com.floatCloud.loveCloud.sysOa.dao.domain
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射


#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#logback配置
logging:
  config: classpath:logging_dev.xml
  path: D:\github_log\logging\loveCloud





