package com.floatCloud.loveCloud.sysOa.dao.mapper;

import com.floatCloud.loveCloud.sysOa.dao.domain.SysAcl;

public interface SysAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insert(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insertSelective(SysAcl record);
}