package com.floatCloud.loveCloud.sysOa.dao.mapper;

import com.floatCloud.loveCloud.sysOa.dao.domain.SysRole;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insertSelective(SysRole record);
}