package com.floatCloud.loveCloud.sysOa.dao.mapper;

import com.floatCloud.loveCloud.sysOa.dao.domain.SysRoleAcl;

public interface SysRoleAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insert(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Apr 27 17:04:36 CST 2019
     */
    int insertSelective(SysRoleAcl record);
}